version: "3.7"
services:
  aspen:
    build: ./
    command: run
    image: aspen:latest
    restart: unless-stopped
    secrets:
      - webhooks.yml
secrets:
  webhooks.yml:
    file: ${WEBHOOKS_FILE}