version: "3.7"
services:
  aspen:
    build: ./
    command: run
    image: houseofmisfits/aspen:latest
    container_name: aspen_${BRANCH_NAME}
    restart: unless-stopped
    secrets:
      - webhooks.yml
secrets:
  webhooks.yml:
    file: ${WEBHOOKS_FILE}